# Generated by Django 5.0.4 on 2024-04-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_food',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='weight',
            field=models.FloatField(),
        ),
    ]
