# Generated by Django 5.0.4 on 2024-05-01 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_add_food_date_add_food_meal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="add_food",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="add_food",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="add_food",
            name="meal",
            field=models.CharField(
                choices=[("B", "Breakfast"), ("L", "Lunch"), ("D", "Dinner")],
                default="B",
            ),
        ),
    ]
