# Generated by Django 5.0.4 on 2024-05-02 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_alter_add_food_calories_alter_add_food_carbs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_food",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
